project_id = "qxeyndsvkfsmkilkzmuc"

[functions.check-dns-records]
verify_jwt = false

[functions.cloudflare-agent]
verify_jwt = false

[functions.check-custom-hostname]
verify_jwt = false

[functions.admin-cloudflare-action]
verify_jwt = false

[functions.get-storefront-bundle]
verify_jwt = false
