
INSERT INTO public.theme_category_briefs
(vertical, subcategory, display_name, prompt_addendum, palette_hints, vocabulary, hero_archetypes, section_priority, image_style, sort_order)
VALUES
-- Healthcare
('services','doctor-clinic','Doctor / Clinic','Independent doctor or small clinic. Emphasise trust, qualifications, consultation hours, and a prominent Book Appointment CTA. Hero should feel calm and clinical, not promotional. Show specialisations, fees, and a clean schedule view.','medical white, trust blue, soft teal, sage','Consultation, OPD, appointment, MBBS, specialisation, patient, prescription, follow-up, family doctor, second opinion','clinic-portrait, doctor-with-stethoscope, calm-waiting-room','{announcement_bar,hero,usp_strip,image_with_text,testimonials,contact_form,newsletter}','clean clinical photography, soft natural light, calm tones',200),
('services','nursing-home','Nursing Home / Multi-Speciality','Multi-doctor nursing home with departments (cardiology, ortho, paediatrics, etc.). Hero must convey 24x7 availability, emergency line, and easy appointment booking. Show department grid, doctor team, in-patient facilities and insurance partners.','hospital white, deep navy trust, emerald accent','Department, in-patient, OPD, ICU, emergency, specialist, on-call, admission, diagnostic','hospital-facade, doctor-team, modern-ward','{announcement_bar,hero,category_grid,usp_strip,image_with_text,testimonials,contact_form,newsletter}','documentary hospital photography, bright corridors, warm humans',201),
('services','dental-clinic','Dental Clinic','Cosmetic and family dentistry. Hero should be bright, confident, and smile-led. Highlight services (whitening, aligners, root canal), pricing transparency, EMI options, and appointment booking.','pearl white, mint, soft coral, charcoal','Smile, aligners, whitening, root canal, scaling, implant, paediatric dentistry, cosmetic','smiling-patient, modern-chair, before-after-smile','{announcement_bar,hero,usp_strip,image_with_text,featured_products,testimonials,newsletter}','crisp dental photography, white backgrounds, confident smiles',202),
('services','physio-rehab','Physiotherapy & Rehab','Physiotherapist or rehab studio offering at-clinic and home-visit sessions. Hero should feel energetic and recovery-focused. Show conditions treated, session packages, and home-visit toggle.','calming sage, soft orange, slate, off-white','Recovery, mobility, pain relief, sports injury, post-surgery, home visit, session package','therapist-with-patient, rehab-equipment, motion-stretch','{announcement_bar,hero,usp_strip,image_with_text,testimonials,featured_products,newsletter}','warm rehab studio photography, motion-blur action shots',203),
('services','ayurveda-clinic','Ayurveda & Wellness Clinic','Authentic Ayurveda clinic / Panchakarma centre. Hero should feel grounded, traditional, premium-wellness. Show therapies, doctor lineage, treatment packages, retreat options.','sandalwood, sage green, ochre, terracotta','Dosha, Panchakarma, abhyanga, vaidya, herbal, classical, retreat, consultation','traditional-therapy, herbs-flatlay, vaidya-portrait','{announcement_bar,hero,image_with_text,usp_strip,featured_products,testimonials,newsletter}','warm earthy photography, brass + herbs, candlelit treatment rooms',204),
('services','veterinary-clinic','Veterinary Clinic','Pet doctor / animal hospital. Hero must feel warm, friendly, pet-positive. Show services (vaccination, grooming, surgery), home-visit option, and emergency line.','warm cream, friendly teal, paw-print orange','Vaccination, deworming, grooming, neuter, home visit, pet wellness, vet on call','vet-with-pet, happy-dog, exam-room','{announcement_bar,hero,usp_strip,image_with_text,testimonials,featured_products,newsletter}','candid pet photography, soft natural light, joyful expressions',205),
('services','diagnostic-lab','Diagnostic Lab / Imaging','Pathology lab or imaging centre with home sample collection. Hero must communicate speed, accuracy, and home-collection booking. Show test packages, lab certifications, sample-pickup toggle.','clinical white, electric blue, lime accent','Home collection, NABL, report, full body checkup, blood test, scan, package','lab-technician, sample-vials, modern-equipment','{announcement_bar,hero,featured_products,usp_strip,image_with_text,testimonials,newsletter}','clean lab photography, blue-lit equipment, precise compositions',206),

-- Beauty Services
('services','unisex-salon','Unisex Salon','Full-service unisex salon. Hero must show stylish interiors and a clear Book Appointment CTA. Show service menu by category (hair, skin, nails), stylist team, packages, and walk-in vs appointment options.','espresso brown, blush, gold accent, cream','Stylist, blow-dry, balayage, manicure, pedicure, facial, package, walk-in, family salon','salon-interior, stylist-at-work, after-look-portrait','{announcement_bar,hero,category_grid,image_with_text,testimonials,featured_products,newsletter}','editorial salon photography, mirror reflections, warm tungsten light',210),
('services','hair-stylist','Independent Hair Stylist','Solo hair stylist or freelance creative. Hero must feel personal, portfolio-led, premium. Show signature looks, before/after, home-visit toggle, and direct DM booking.','jet black, hot pink accent, soft cream','Cut, colour, balayage, keratin, bridal hair, home visit, signature look','stylist-portrait, signature-cut, before-after','{announcement_bar,hero,image_with_text,testimonials,featured_products,newsletter,contact_form}','high-fashion portrait photography, dramatic lighting, hero close-ups',211),
('services','barber-shop','Barber / Men''s Grooming','Modern barber shop or men''s grooming studio. Hero must feel masculine, crafted, no-nonsense. Show beard styles, fade gallery, hot-towel shave, membership plans.','charcoal, leather brown, brass, off-white','Fade, beard sculpt, hot-towel shave, classic crop, membership, walk-in','barber-portrait, beard-detail, vintage-chair','{announcement_bar,hero,image_with_text,featured_products,testimonials,usp_strip,newsletter}','moody documentary photography, leather + brass textures, grain',212),
('services','spa-wellness','Spa & Wellness Centre','Luxury day spa or wellness retreat. Hero must feel serene, sensorial, premium. Show signature treatments, couple suites, membership tiers, and gift cards.','warm beige, sage, copper, soft white','Aromatherapy, signature massage, couple suite, hammam, day pass, membership','calm-treatment-room, oil-pouring, serene-portrait','{announcement_bar,hero,image_with_text,featured_products,testimonials,values,newsletter}','soft-focus spa photography, candle glow, sumptuous textures',213),
('services','nail-studio','Nail Studio','Modern nail bar / nail art studio. Hero must feel playful, colourful, Instagrammable. Show nail-art gallery, extensions menu, party packages, and walk-in slots.','soft pink, lilac, neon accent, cream','Gel, extensions, nail art, French, ombre, party, walk-in, instant-book','nail-art-closeup, hands-styled, studio-flatlay','{announcement_bar,hero,featured_products,image_with_text,testimonials,usp_strip,newsletter}','high-saturation product macro, pastel backgrounds, playful props',214),
('services','makeup-mehendi','Makeup & Mehendi Artist','Freelance bridal makeup / mehendi artist. Hero must feel bridal, festive, premium-portfolio. Show packages (engagement, bride, party), home-visit zones, and inquiry form.','blush rose, deep maroon, gold leaf, ivory','Bridal, engagement, party makeup, airbrush, mehendi, home visit, destination','bride-portrait, mehendi-hands, behind-the-scenes','{announcement_bar,hero,image_with_text,testimonials,featured_products,contact_form,newsletter}','romantic bridal photography, gold light, intricate detail close-ups',215),
('services','home-visit-pro','Home-Visit Professional','At-home service specialist (any vertical: doctor, salon, physio, pet groomer). Hero must lead with pincode-check + Home Visit toggle. Show coverage map, travel-fee transparency, slot picker.','trust blue, fresh green, soft white','Pincode, home visit, travel fee, on-call, doorstep service, slot, family pack','professional-at-door, kit-flatlay, friendly-handshake','{announcement_bar,hero,usp_strip,image_with_text,contact_form,testimonials,newsletter}','warm documentary photography, doorstep moments, real customers',216)
ON CONFLICT (vertical, subcategory) DO UPDATE SET
  display_name     = EXCLUDED.display_name,
  prompt_addendum  = EXCLUDED.prompt_addendum,
  palette_hints    = EXCLUDED.palette_hints,
  vocabulary       = EXCLUDED.vocabulary,
  hero_archetypes  = EXCLUDED.hero_archetypes,
  section_priority = EXCLUDED.section_priority,
  image_style      = EXCLUDED.image_style,
  sort_order       = EXCLUDED.sort_order,
  is_active        = true,
  updated_at       = now();
