// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const checkIsDemoSession = () => {
  if (typeof window === 'undefined') return false;
  
  const params = new URLSearchParams(window.location.search);
  const hasAutoLogin = params.has('email') && params.has('password');
  
  if (hasAutoLogin) {
    try {
      window.sessionStorage.setItem('is_demo_session', 'true');
      return true;
    } catch (e) {
      return false;
    }
  }
  
  try {
    if (window.sessionStorage.getItem('is_demo_session') === 'true') {
      return true;
    }
  } catch (e) {}
  
  return false;
};

const isDemo = checkIsDemoSession();
const storage = typeof window !== 'undefined'
  ? (isDemo ? window.sessionStorage : window.localStorage)
  : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: isDemo ? 'sb-demo-auth-token' : undefined,
    broadcastTabSync: !isDemo, // Disable cross-tab synchronization for demo session to prevent logging out other tabs (like partner dashboard)
  } as any
});